### ISSUE TITLE
update repository 404 not found

### ISSUE THREAD

**Issue by alicanuzun** [AUV-IITK/AUVWiki#15]
I am trying to install gazebo7 to my ubuntu 14.04.5 LTS version with ros indigo. I installed the ros-indigo-desktop-full and purge gazebo with `sudo apt-get purge gazebo*`. I followed the instructions on [this](https://github.com/AUV-IITK/AUVWiki/wiki/Installing-Gazebo7-with-ROS-Indigo) link. I added the repository to source list and wget returned status OK. after running `sudo apt-get update` I get the following error:

> N: Ignoring file 'gazebo.key' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
W: Failed to fetch http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/lsb_release/-cs/binary-amd64/Packages  404  Not Found

>W: Failed to fetch http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/lsb_release/main/binary-amd64/Packages  404  Not Found

>W: Failed to fetch http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/lsb_release/-cs/binary-i386/Packages  404  Not Found

>W: Failed to fetch http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/lsb_release/main/binary-i386/Packages  404  Not Found

>E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ShikherVerma** [comment]
That's because http://packages.osrfoundation.org/gazebo/ubuntu-stable/dists/ now does not have any `lsb_release` folder. So it can't find `lsb_release/~cs/binary...` file. Use the [lastest install instructions](http://gazebosim.org/tutorials?tut=install_ubuntu&cat=install)

**Comment by Mayankm96** [comment]
Closing this issue since it's inactive. Kindly reopen it if it is still unresolved.
